<?php
/**
 * Survey app configuration.
 *
 * Update `$formDefinition['fields']` to match the Google Form questions.
 * Set SURVEY_ADMIN_PASSWORD on the server to protect exports.
 */

$formDefinition = [
    'title' => '訪問看護記録（テスト）',
    'description' => 'Googleフォームの設問をもとにした自作フォームです。※記録画像のファイルアップロードはこの簡易版では対応していません。URLやメモで代用してください。',
    'thank_you_message' => 'ご回答ありがとうございました！',
    'fields' => [
        ['key' => 'email', 'label' => 'メールアドレス', 'type' => 'email', 'required' => true],
        ['key' => 'visitor_name', 'label' => '訪問先（訪問者様のお名前）', 'type' => 'text', 'required' => true],
        ['key' => 'visitor_id', 'label' => '訪問者様ID', 'type' => 'text', 'required' => false],
        ['key' => 'nurse1', 'label' => '訪問した看護師（1）（氏名）', 'type' => 'text', 'required' => true],
        ['key' => 'nurse2', 'label' => '訪問した看護師（2）（氏名）', 'type' => 'text', 'required' => false],
        ['key' => 'insurance_type', 'label' => '保険種別', 'type' => 'select', 'required' => true, 'options' => ['介護保険', '医療保険', 'その他']],
        ['key' => 'visit_date', 'label' => '訪問日', 'type' => 'date', 'required' => true],
        ['key' => 'visit_start', 'label' => '訪問開始時刻', 'type' => 'time', 'required' => true],
        ['key' => 'visit_end', 'label' => '訪問終了時刻', 'type' => 'time', 'required' => true],
        ['key' => 'observation_notes', 'label' => '観察事項', 'type' => 'textarea', 'required' => false],
        ['key' => 'blood_pressure', 'label' => '血圧（mmHg）', 'type' => 'text', 'required' => false, 'placeholder' => '例: 120/80'],
        ['key' => 'pulse_rate', 'label' => '脈拍 (回/分)', 'type' => 'number', 'required' => false],
        ['key' => 'pulse_quality', 'label' => '脈拍 (性状)', 'type' => 'select', 'required' => false, 'options' => ['整', '不整']],
        ['key' => 'temperature', 'label' => '体温 (℃)', 'type' => 'number', 'required' => false, 'placeholder' => '例: 36.5'],
        ['key' => 'temperature_site', 'label' => '体温 (測定部位)', 'type' => 'select', 'required' => false, 'options' => ['腋窩', '額', '口腔', '肛門']],
        ['key' => 'resp_rate', 'label' => '呼吸 (回/分)', 'type' => 'number', 'required' => false],
        ['key' => 'resp_quality', 'label' => '呼吸 （性状)', 'type' => 'text', 'required' => false],
        ['key' => 'spo2', 'label' => 'SpO2 (%)', 'type' => 'number', 'required' => false],
        ['key' => 'consciousness', 'label' => '意識の状態', 'type' => 'text', 'required' => false],
        ['key' => 'mobility', 'label' => '身のこなし', 'type' => 'text', 'required' => false],
        ['key' => 'appetite', 'label' => '食欲', 'type' => 'select', 'required' => false, 'options' => ['有', '無']],
        ['key' => 'hydration', 'label' => '水分摂取 (ml/日)', 'type' => 'number', 'required' => false],
        ['key' => 'sleep_quality', 'label' => '睡眠（状態）', 'type' => 'select', 'required' => false, 'options' => ['熟睡', '普通', '浅い', '不眠']],
        ['key' => 'sleep_medication', 'label' => '睡眠（眠剤）', 'type' => 'select', 'required' => false, 'options' => ['眠剤あり', '眠剤なし']],
        ['key' => 'sleep_daynight', 'label' => '睡眠（昼夜リズム）', 'type' => 'select', 'required' => false, 'options' => ['昼夜逆転あり', '昼夜逆転なし']],
        ['key' => 'sleep_other', 'label' => '睡眠 その他', 'type' => 'text', 'required' => false],
        ['key' => 'bowel_per_day', 'label' => '排便(回/日)', 'type' => 'number', 'required' => false],
        ['key' => 'urine_ml_per_day', 'label' => '排尿(ml/日)', 'type' => 'number', 'required' => false],
        ['key' => 'urine_times_per_day', 'label' => '排尿(回/日)', 'type' => 'number', 'required' => false],
        ['key' => 'medication_notes', 'label' => '服薬 / 癌痛 / その他', 'type' => 'textarea', 'required' => false],
        [
            'key' => 'care_support',
            'label' => '看護・介護・診察の援助（該当するものすべて）',
            'type' => 'checkboxes',
            'required' => false,
            'options' => [
                '看護・介護・診察の援助',
                '看護・介護・診断の援助',
                'バイタルサイン',
                '一般状態の観察',
                '健康相談',
                'メンタルケア',
                '食事・飲水介助',
                '栄養管理 (経口・胃瘻・HPN)',
                '栄養指導',
                '排泄・排泄介助',
                '浣腸・摘便',
                'オムツ交換',
                'ストーマ/パウチ交換',
                '入力介助',
                'シャワー浴',
                '清拭',
                '口腔ケア',
                '部分浴 (手・足・陰部)',
                '洗髪',
                '整容',
                '褥衣・寝具交換',
                '爪切り・耳垢除去',
                '移動介助',
                '体位変換',
                'タッピング',
                'マッサージ',
                '〇〇予防・処置',
                '創の処置',
                '軟膏・ローション塗布',
                '外用薬貼付',
                '導尿・膀胱洗浄',
                '留置カテーテル交換・管理',
                '腎チューブの交換・管理',
                '吸引',
                'カニューレ交換・管理',
                '首ヒモ交換・介助',
                '注射 (IS・IM・IV・Div)',
                'インスリン注射指導',
                '血糖チェック',
                '自己導尿指導',
                '服薬指導・管理・介助',
                '家族健康チェック',
                '受診推奨',
                '点眼',
                '介護・看護指導',
                'CAPD指導・管理',
                'その他',
            ],
        ],
        ['key' => 'oxygen_flow', 'label' => '酸素吸入・管理（g/min）', 'type' => 'text', 'required' => false],
        ['key' => 'weight', 'label' => '体重測定（kg）', 'type' => 'number', 'required' => false, 'placeholder' => '例: 50.2'],
        [
            'key' => 'rehab_items',
            'label' => 'リハビリ（該当するものすべて）',
            'type' => 'checkboxes',
            'required' => false,
            'options' => [
                'ROM訓練・ストレッチ',
                '筋力訓練',
                '座位・立位訓練',
                '歩行訓練',
                'ADL訓練',
                '知的訓練',
                'その他',
            ],
        ],
        [
            'key' => 'contact_status',
            'label' => '連絡状況（該当するものすべて）',
            'type' => 'checkboxes',
            'required' => false,
            'options' => [
                '医師',
                'ケアマネージャー',
                'ヘルパー',
                '家族',
                '薬剤師',
                '福祉用具専門相談員',
                'その他',
            ],
        ],
        ['key' => 'soap_note', 'label' => '記録 「S（主観）/O（客観）/A（評価）/P（計画）」', 'type' => 'textarea', 'required' => false],
        ['key' => 'record_images', 'label' => '記録画像（URLやメモで記載してください／ファイルアップロード非対応）', 'type' => 'textarea', 'required' => false],
        ['key' => 'next_instructions', 'label' => '次回伝達事項', 'type' => 'textarea', 'required' => false],
        ['key' => 'next_visit_date', 'label' => '次回訪問日', 'type' => 'date', 'required' => false],
    ],
];

$databasePath = __DIR__ . '/data/survey.sqlite';

// Optional: protect export/download endpoints with a password.
$adminPassword = getenv('SURVEY_ADMIN_PASSWORD') ?: 'suzaki1201';

// Allow local overrides without touching this file (create config.local.php if needed).
$localConfig = __DIR__ . '/config.local.php';
if (file_exists($localConfig)) {
    require $localConfig;
}
