name: Deploy to Xserver

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: sv7749.xserver.jp
        username: cenleaf
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /cenleaf.com/public_html/
        protocol: ftps
        port: 21
        dangerous-clean-slate: true
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.DS_Store
          README.md
          .github/**
          docs/**
          backup/**
          .env
          FTP情報